[phases.setup]
nixPkgs = ['nodejs_18', 'python311']

[phases.install]
dependsOn = ['setup']
cmds = [
    'pip install -r requirements.txt',
    'npm ci --verbose'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'echo "=== Starting React Build ==="',
    'npm run build',
    'echo "=== Build completed ==="',
    'ls -la dist/',
    'echo "Build artifacts:"',
    'find dist -type f | head -20'
]

[start]
cmd = 'python app.py'