[phases.setup]
nixPkgs = ['nodejs_18', 'python311']

[phases.install]
dependsOn = ['setup']
cmds = [
    'pip install -r requirements.txt',
    'npm install'
]

[phases.build]
dependsOn = ['install']
cmds = [
    'npm run build',
    'ls -la dist/',
    'echo "Build completed - checking files:"',
    'find dist -type f | head -10'
]

[start]
cmd = 'python app.py'